[package]
name = "rust_msa"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
autodiff = { path = "/u/drehwald/prog/rust/library/autodiff" }

[profile.release]
lto = "fat"

[profile.dev]
lto = "fat"
